#!/usr/bin/python
import curses
from time import sleep
from rover import rover
# INIT CURSES STUFF
screen = curses.initscr()
curses.start_color()
curses.use_default_colors()
curses.curs_set(0)
screen.clear()
curses.noecho()
dimensions = screen.getmaxyx()
ymax = dimensions[0]
xmax = dimensions[1]

# CONNECT TO ROVER
my_rover = rover('/dev/tty.usbserial-AJV9OOBQ')
screen.addstr(1, 1, 'ROVER1 Remote Terminal connecting to ' + my_rover.address, curses.A_STANDOUT)
screen.refresh()
my_rover.connect()
if my_rover.connected is True:
    screen.addstr(1, 1, 'ROVER1 Remote Terminal connected on ' + my_rover.address, curses.A_STANDOUT)
    screen.refresh()
else:
    exit()
while my_rover.connected is True:
    my_rover.read()
    my_rover.log2curses(screen)
    sleep(0.2)
exit()
